CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(40) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP NOT NULL
);

CREATE TABLE games (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode            VARCHAR(20) NOT NULL,
    player_count    INT NOT NULL,
    ruleset_version VARCHAR(20) NOT NULL,
    seed            BIGINT NOT NULL,
    created_at      TIMESTAMP NOT NULL
);

CREATE TABLE game_players (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id      BIGINT NOT NULL REFERENCES games (id),
    seat         INT NOT NULL,
    user_id      BIGINT REFERENCES users (id),
    display_name VARCHAR(40) NOT NULL,
    is_bot       BOOLEAN NOT NULL,
    final_rank   INT NOT NULL,
    final_score  INT NOT NULL
);

CREATE TABLE rounds (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id      BIGINT NOT NULL REFERENCES games (id),
    round_number INT NOT NULL,
    dealer_seat  INT NOT NULL,
    contract     VARCHAR(20) NOT NULL
);

CREATE TABLE round_scores (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id BIGINT NOT NULL REFERENCES rounds (id),
    seat     INT NOT NULL,
    points   INT NOT NULL
);
